palladiumkenya/openmrs-module-insuranceclaims

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimDiagnosisServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimResponseServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, omod/pom.xml, omod/src/main/resources/config.xml
Fix base openmrs data util functions
=> Fix base openmrs data util functions

api/pom.xml, omod/pom.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, pom.xml
=> Code Cleanup

.vscode/launch.json, api/src/main/java/org/openmrs/module/insuranceclaims/InsuranceClaimsActivator.java, omod/src/main/resources/config.xml
=> enable debugging

api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimDiagnosisServiceImpl.java, api/src/main/resources/components/fhirComponents.xml, api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/forms/impl/ClaimFormServiceImpl.java
=> Fix concept source issues

api/src/main/java/org/openmrs/module/insuranceclaims/InsuranceClaimsActivator.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimDiagnosisServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimItemServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimResponseServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/PatientUtil.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/SpecialComponentUtil.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, api/src/main/resources/moduleApplicationContext.xml
Added extra R4 resources to the FHIR payload
=> Added extra R4 resources to the FHIR payload

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
Sending data to remote can be done later. We attempt once.
=> Sending data to remote can be done later. We attempt once.

api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/InsuranceClaimDao.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/impl/InsuranceClaimDaoImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/InsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/impl/InsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/task/PullClaimResponsesTask.java, api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
Added the pull task plus other endpoints
=> Added the pull task plus other endpoints

api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java, omod/src/main/resources/webModuleApplicationContext.xml
=> Add generic search

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/task/PullClaimResponsesTask.java, omod/pom.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java, pom.xml
Currently adding the CoverageEligibilityRequest endpoint
=> Currently adding the CoverageEligibilityRequest endpoint

api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
New coverage eligibility request
=> New coverage eligibility request

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
Send the eligibility request to remote server
=> Send the eligibility request to remote server

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/ClaimHttpRequest.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/ClientConstants.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/ClaimHttpRequestImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaim.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/FHIREligibilityService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/FHIRInsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIREligibilityServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/util/ClaimsUtils.java, api/src/main/java/org/openmrs/module/insuranceclaims/util/ReferencesUtil.java, api/src/main/resources/components/fhirComponents.xml, api/src/main/resources/liquibase.xml, api/src/main/resources/moduleApplicationContext.xml, omod/pom.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/forms/NewClaimForm.java, omod/src/main/java/org/openmrs/module/insuranceclaims/forms/impl/ClaimFormServiceImpl.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, pom.xml
1. added a bundle to handle coverageeligibilityrequest
2. a. Refactor Coverage Eligibility Request to use Bundle
b. Refactor claim and pre-auth request to use Bundle 
Todo:
c. Refactor Coverage Eligibility Response to use Bundle
d. Refactor claim and pre-auth Response to use Bundle
=> added a bundle to handle coverageeligibilityrequest

api/pom.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, omod/src/main/resources/config.xml, pom.xml
Interim for insurance cover checks
=> provide interim for checking insurance coverage

api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/ClaimHttpRequestImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/InsuranceClaimDao.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/impl/InsuranceClaimDaoImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/InsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/FHIRInsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimItemServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/impl/InsuranceClaimServiceImpl.java, api/src/main/resources/components/fhirComponents.xml, api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java
Fixed claims FHIR payload  and added API search functionality
=> Fixed claims FHIR payload  and added API search functionality

.github/workflows/CI-DEV.yml
=> Update CI-DEV.yml - Avoid license format

api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/ClaimHttpRequestImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/PractitionerUtil.java, api/src/main/resources/components/fhirComponents.xml, api/src/main/resources/moduleApplicationContext.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/forms/impl/ClaimFormServiceImpl.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java
Added new practitioner identifiers to FHIR payload. Provider National ID and Licence number
=> Added new practitioner identifiers to FHIR payload. Provider National ID and Licence number

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, omod/src/main/resources/config.xml
Added proxy for Packages And Interventions
=> Added proxy for Packages And Interventions

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
=> Updated change in Eligibility request response formatted as a json object with expiry date and token

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202025-01-26%2015-04-17.png
=> Reverting HEI UAT Authentication mechanism returning an object response

api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIREligibilityServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/GeneralUtil.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/InsuranceClaimConstants.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java, omod/src/main/resources/config.xml
Fix claim fhir outgoing payload
=> Fix claim fhir outgoing payload

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, omod/pom.xml, pom.xml
=> Bump to ver1.0.4

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java
Added ID field to claims provider in FHIR payload
=> Added ID field to claims provider in FHIR payload

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/InsuranceClaimDao.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/impl/InsuranceClaimDaoImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/InsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/impl/InsuranceClaimServiceImpl.java, omod/pom.xml, omod/src/main/java/org/openmrs/module/insuranceclaims/forms/impl/ClaimFormServiceImpl.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java, pom.xml
Fix claim from and to time and listing order
=> Fix claim from and to time and listing order

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/GeneralUtil.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/InsuranceClaimConstants.java
Fixed location attribute and patient identifier for claim payload
=> Fixed location attribute and patient identifier for claim payload

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimItemServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java
Set the claim total and items total to zero for now
=> Set the claim total and items total to zero for now

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/GeneralUtil.java
=> Updated HIE insurance Authentication : Introduced a config to toggle between post and get auth modes

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/GeneralUtil.java
=> Updated the facility registration code to use global property as the location attribute does not exist

api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java
Added care team to claim payload
=> Added care team to claim payload

api/src/main/java/org/openmrs/module/insuranceclaims/api/client/ClaimHttpRequest.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/ClaimHttpRequestImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaim.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, api/src/main/resources/liquibase.xml
=> Added response uuid to claim

api/src/main/resources/liquibase.xml
Fixed liquibase on response uuid
=> Fixed liquibase on response uuid

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/FhirBaseMessageConverter.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/FhirBundleMessageConverter.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/FhirOperationOutcomeMessageConverter.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java, omod/pom.xml, pom.xml
Add http response for bundle and operation outcome
=> Add http response for bundle and operation outcome

api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/InsuranceClaimDao.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/dao/impl/InsuranceClaimDaoImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/ClaimTransactionStatus.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaimStatus.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/ClaimTransactionStatusService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/InsuranceClaimService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/impl/InsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/util/ConstantValues.java, omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
* creates an endpoint to update the claim's status from the payment aggregator
=> (feat): Update claim status 

omod/src/main/java/org/openmrs/module/insuranceclaims/web/resource/ClaimResource.java
* Adds response UUID to the claim endpoint to facilitate updating of the claim status
=> (fix): Add response UUID

api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaimStatus.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/impl/InsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/request/impl/ExternalApiRequestImpl.java
- Update the allowable claim statuses
- Update the claim code value with the claim id ie. ("C-002")
=> (fix): update claim status item and claim code value

omod/src/main/java/org/openmrs/module/insuranceclaims/web/controller/InsuranceClaimResourceController.java
=> Updated EligibilityCoverageRequest endpoint to make patient uuid optional as the national ID is the mandatory requirement

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/api/client/impl/FhirRequestClient.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaim.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/InsuranceClaimAttachment.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/model/SupportingDocuments.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/FHIRClaimItemService.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRClaimItemServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/impl/FHIRInsuranceClaimServiceImpl.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/GeneralUtil.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/service/fhir/util/InsuranceClaimConstants.java, api/src/main/java/org/openmrs/module/insuranceclaims/forms/NewClaimForm.java, api/src/main/java/org/openmrs/module/insuranceclaims/forms/impl/ClaimFormServiceImpl.java, api/src/main/resources/liquibase.xml, omod/pom.xml, pom.xml
KHP3-8496 - Sync KenyaEMR with Latest HIE enhancements
- KHP3-8523 - New HIE Workflows planning -- done
- KHP3-8524 - Create and send new HIE Prescriptions payload through interop -- WIP
- KHP3-8525 - Maternity differentiation from normal PHC (Primary Health Care) to SHIF -- WIP
- KHP3-8526 - Maternity supporting documents upload -- WIP
- KHP3-8527 - Generate and Send Maternity payload -- WIP
=> Sync with HIE Advancements mombasa sept 2025

api/pom.xml, api/src/main/java/org/openmrs/module/insuranceclaims/InsuranceClaimsActivator.java, api/src/main/java/org/openmrs/module/insuranceclaims/advice/CreateClaimOnCheckout.java, api/src/main/java/org/openmrs/module/insuranceclaims/api/task/PullClaimResponsesTask.java, omod/pom.xml, pom.xml
=> Fix logging issue
